idf_component_register(
    SRCS
        "main.c"
        "bsp/bsp_board.c"
        "bsp/bsp_display.c"
        "sprite/clawd.c"
        "sprite/text.c"
        "model/sessions.c"
        "link/link.c"
        "bsp/bsp_touch.c"
        "audio/audio.c"
        "input/input.c"
        "ui/pages.c"
        "ui/pager.c"
    INCLUDE_DIRS
        "."
        "bsp"
        "sprite"
        "model"
        "link"
        "input"
        "ui"
        "audio"
    REQUIRES
        driver
        esp_lcd
        esp_psram
        esp_timer
        json
)
